/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_HelloWorld */

#ifndef _Included_JNI_HelloWorld
#define _Included_JNI_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_HelloWorld
 * Method:    one
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_HelloWorld_one
  (JNIEnv *, jclass);

/*
 * Class:     JNI_HelloWorld
 * Method:    two
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_HelloWorld_two
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
